name: CD Pipeline


on:
   workflow_run:
    # CI Pipeline이 실행된 후 실행
    workflows: [ "CI Pipeline" ]
    types:
      - completed

jobs:
  deploy:

    # 리눅스 서버의 Runner에서 실행
    runs-on: self-hosted

    steps:

      # 현재 레포지토리 가져오기
      - name: Checkout repository
        uses: actions/checkout@v4

      # Docker 로그인
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # Docker 이미지 Pull
      - name: Pull Docker image
        run: docker pull  ${{ secrets.DOCKER_USERNAME }}/ballog-server:latest

      # ballog-server가 실행중인 경우 중지
      - name: Stop ballog-server
        run: docker stop ballog-server || true && docker rm ballog-server || true

      # spring-boot-app만 다시 실행
      - name: Deploy with Docker Compose
        run: |
          source ~/.bashrc
          docker-compose stop spring-boot-app && docker-compose rm -f spring-boot-app
          docker-compose up -d spring-boot-app
